variables:
  REACT_APP_ENV: $REACT_APP_ENV
  REACT_APP_ENV_PROD: $REACT_APP_ENV_PROD
  REACT_APP_CRYPT_KEY: $REACT_APP_CRYPT_KEY
  REACT_APP_API_BASE: $REACT_APP_API_BASE
  REACT_APP_API_BASE_PROD: $REACT_APP_API_BASE_PROD
  REACT_APP_OTP_ONLY_DOMAINS: $REACT_APP_OTP_ONLY_DOMAINS
  S3_BUCKET_NAME_UAT: $S3_BUCKET_NAME_UAT
  S3_BUCKET_NAME_PROD: $S3_BUCKET_NAME_PROD
  S3_BUCKET_NAME_PORTAL: $S3_BUCKET_NAME_PORTAL
  DISTRIBUTION_UAT: $DISTRIBUTION_UAT
  DISTRIBUTION_PROD: $DISTRIBUTION_PROD
  DISTRIBUTION_PORTAL: $DISTRIBUTION_PORTAL
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION

stages:
  - build
  - deploy

build-uat:
  image: node:14
  stage: build
  only:
    - development
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
  variables:
    CI: ''
  script:
    - yarn install
    - export REACT_APP_ENV=$REACT_APP_ENV
    - export REACT_APP_CRYPT_KEY=$REACT_APP_CRYPT_KEY
    - export REACT_APP_API_BASE=$REACT_APP_API_BASE
    - export REACT_APP_OTP_ONLY_DOMAINS=$REACT_APP_OTP_ONLY_DOMAINS
    - CI=''
    - yarn build
  artifacts:
    paths:
      - build
    expire_in: 1 hour

deploy-uat:
  stage: deploy
  environment:
    name: uat
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  only:
    - development
  script:
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
    - aws s3 sync ./build/ s3://$S3_BUCKET_NAME_UAT --delete
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_UAT --paths "/*"

build-portal:
  image: node:14
  stage: build
  only:
    - prod-portal
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
  variables:
    CI: ''
  script:
    - yarn install
    - export REACT_APP_ENV=$REACT_APP_ENV_PROD
    - export REACT_APP_CRYPT_KEY=$REACT_APP_CRYPT_KEY
    - export REACT_APP_API_BASE=$REACT_APP_API_BASE_PROD
    - export REACT_APP_OTP_ONLY_DOMAINS=$REACT_APP_OTP_ONLY_DOMAINS
    - CI=''
    - yarn build
  artifacts:
    paths:
      - build
    expire_in: 1 hour

deploy-portal:
  stage: deploy
  environment:
    name: portal
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  only:
    - prod-portal
  script:
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
    - aws s3 sync ./build/ s3://$S3_BUCKET_NAME_PORTAL --delete
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_PORTAL --paths "/*"

build-prod:
  image: node:14
  stage: build
  only:
    - prod
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules
  variables:
    CI: ''
  script:
    - yarn install
    - export REACT_APP_ENV=$REACT_APP_ENV_PROD
    - export REACT_APP_CRYPT_KEY=$REACT_APP_CRYPT_KEY
    - export REACT_APP_API_BASE=$REACT_APP_API_BASE_PROD
    - export REACT_APP_OTP_ONLY_DOMAINS=$REACT_APP_OTP_ONLY_DOMAINS
    - CI=''
    - yarn build
  artifacts:
    paths:
      - build
    expire_in: 1 hour

deploy-prod:
  stage: deploy
  environment:
    name: production
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  only:
    - prod
  script:
    - aws --version
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_DEFAULT_REGION
    - aws s3 sync ./build/ s3://$S3_BUCKET_NAME_PROD --delete
    - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_PROD --paths "/*"