export const resources_id = {
  navigation: 'navigation',
  dashboard: 'dashboard',
  creditReload: 'credit_reload',
  withheld: 'withheld',
  renewal: 'renewal',
  transports: 'transports',
  transportPassbook: 'transports_passbook',
  collectionRemark: 'collection_remark',
  nocLetter: 'noc',
  settings: 'settings',
  callRequest: 'call_request',
  users: 'users',
  preSubmit: 'pre_submit',
  exception: 'exception',
  report: 'report',
  dealershipNavigation: 'dealership_navigation',
  dealership: 'dealership',
  dealer: 'dealer',
  scoreCard: 'score_card',
  loansList: 'loans_list',
  personalDiscussion: 'personal_discussion',
  docChecklist: 'doc_checklist',
  transporters: 'transporters',
  fleetOperator: 'fleet_operator'
}

export const action_id = {
  navigation: {

  },
  dashboard: {
    submitted_documents :'sub_docs',
    submitted_rowclick :'submitted_rowclick',
    submitted_edit_loantype :'submitted_edit_loantype',
    submitted_send_for_review :'submitted_send_for_review',
    submitted_esign :'submitted_esign',
    pr_rowclick :'pr_rowclick',
    pr_resubmit :'pr_resubmit',
    pr_reject :'pr_reject',
    pr_send_for_approval :'pr_send_for_approval',
    pr_edit_loantype :'pr_edit_loantype',
    pa_rowclick :'pa_rowclick',
    pa_documents :'pa_documents',
    pa_resubmit :'pa_resubmit',
    pa_reject :'pa_reject',
    pa_approve :'pa_approve',
    pa_edit_loantype :'pa_edit_loantype',
    appr_attachments :'appr_attachments',
    appr_documents :'appr_documents',
    appr_rowclick :'appr_rowclick',
    appr_resubmit :'appr_resubmit',
    disb_appl_reject :'disb_appl_reject',
    disb_appl_approve :'disb_appl_approve',
    disb_appl_rowclick :'disb_appl_rowclick',
    disb_appd_rowclick :'disb_appd_rowclick',
    disb_appd_add_disb_amount :'disb_appd_add_disb_amount',
    disb_rowclick :'disb_rowclick',
    disb_resubmit :'disb_resubmit',
    disb_details_action :'disb_details_action',
    disb_add_disb_amount :'disb_add_disb_amount',
    rej_rowclick :'rej_rowclick',
    rej_resubmit :'rej_resubmit',
    LOS_Switch :'LOS_Switch',
    External_Switch :'External_Switch',
    loan_submit :'loan_submit',
  },
  creditReload: {
    create: 'request:create',
    decline: 'request:decline',
    disburse: 'request:disburse',
  },
  withheld: {
    create: 'request:create',
    resolve: 'request:resolve',
    delete: 'request:delete',
  },
  renewal: {
    sanctionLetter: 'sanction_letter',
    loanAgreement: 'loan_agreement',
    esignApplication: 'esign_application'
  },
  transportPassbook: {
    upload: 'upload_statement',
    download: 'download_statement',
    share: 'share_statement'
  },
  nocLetter: {
    raiseRequest: 'noc:request'
  },
  dealershipNavigation: {
    dealership: 'dealership',
    dealers: 'dealers',
    scoreCard: 'score_card',
    loansList: 'loans_list',
    personalDiscussion: 'personal_discussion',
    docChecklist: 'document_checklist',
    transporters: 'transporters',
    fleetOperator: 'fleet_operator'
  },
  dealership: {
    edit: 'dealership:edit',
    crimeCheck: 'dealership:crimeCheck'
  },
  dealer: {
    dealerAdd: 'dealer:add',
    dealerEdit: 'dealer:edit',
    dealerCrimeCheck: 'dealer:crimeCheck',
    dealerCreditCheck: 'dealer:creditCheck',
    dealerStatus: 'dealer:status',
    coapplicantAdd: 'coapplicant:add',
    coapplicantEdit: 'coapplicant:edit',
    coapplicantCrimeCheck: 'coapplicant:crimeCheck',
    coapplicantCreditCheck: 'coapplicant:creditCheck',
    coapplicantStatus: 'coapplicant:status',
    guarantorAdd: 'guarantor:add',
    guarantorEdit: 'guarantor:edit',
    guarantorCrimeCheck: 'guarantor:crimeCheck',
    guarantorCreditCheck: 'guarantor:creditCheck',
    guarantorStatus: 'guarantor:status',
    Vkyc: 'vkyc',
  },
  scoreCard: {
    upload: 'scorecard:upload',
  },
  loansList: {
    action: 'loans_list:action',
    statement: 'account_statement',
    applicationStatus: 'application_status',
  },
  personalDiscussion: {
    omcView: 'omc:view',
    omcEdit: 'omc:edit',
    businessView: 'business:view',
    businessEdit: 'business:edit',
    outletView: 'outlet:view',
    outletEdit: 'outlet:edit',
    infrastructureView: 'infrastructure:view',
    infrastructureEdit: 'infrastructure:edit',
    infrastructureAddTanker: 'infrastructure:add_tanker',
    assetView: 'asset:view',
    assetEdit: 'asset:edit',
    assetAdd: 'asset:add',
    assetDelete: 'asset:delete',
    bankView: 'bank:view',
    bankAdd: 'bank:add',
    bankEdit: 'bank:edit',
    bankDelete: 'bank:delete',
    bankVerify: 'bank:verify',
    loanView: 'loan:view',
    loanAdd: 'loan:add',
    loanEdit: 'loan:edit',
    loanDelete: 'loanDelete',
    incomeExpenceView: 'income_expence:view',
    incomeAdd: 'income:add',
    incomeEdit: 'income:edit',
    incomeDelete: 'income:delete',
    expenceAdd: 'expence:add',
    expenceEdit: 'expence:edit',
    expenceDelete: 'expence:delete',
    thirdPartyView: 'third_party:view',
    referenceAdd: 'reference:add',
    referenceEdit: 'referenceEdit',
    referenceDelete: 'referenceDelete',
    otherView: 'other:view',
    bunkAdd: 'bunk:add',
    bunkEdit: 'bunk:edit',
    bunkDelete: 'bunk:delete',
    creditPdView: 'credit_pd:view',
    creditPdEdit: 'credit_pd:edit',
    callLogView: 'call_log:view',
    callInitiate: 'call:initiate',
    callLogDelete: 'call_log:delete',
    pdReport: 'pd:report'
  },
  docChecklist: {
    upload: 'doc:upload',
    edit: 'doc_name:edit',
    delete: 'doc:delete',
  },
  transporters: {
    addOwner: 'owner:add',
    editOwner: 'owner:edit',
    addTransport: 'transport:add',
    editTransport: 'transport:edit',
  },
  fleetOperator: {
    add: 'operator:add',
    edit: 'operator:edit'
  },
  settings: {
    zones :'zones',
    states :'states',
    regions :'regions',
    city :'city',
    omcs :'omcs',
    business :'business',
    loan :'loan',
    asset :'asset',
    products :'products',
    assign_role_products :'assign_role_products',
    collectionRemark :'collection_remark',
    zonesAdd :'zones:add',
    statesAdd :'states:add',
    regionsAdd :'regions:add',
    cityAdd :'city:add',
    omcsAdd :'omcs:add',
    businessAdd :'business:add',
    loanAdd :'loan:add',
    assetAdd :'asset:add',
    productsAdd :'products:add',
    addign_role_productsAdd :'addign_role_products:add',
    collection_remarkAdd :'collection_remark:add',
    statesDelete :'states:delete',
    regionsDelete :'regions:delete',
    omcsDelete :'omcs:delete',
    businessDelete :'business:delete',
    loanDelete :'loan:delete',
    assetDelete :'asset:delete',
    zonesUpdate :'zones:update',
    statesUpdate :'states:update',
    regionsUpdate :'regions:update',
    cityUpdate :'city:update',
    omcsUpdate :'omcs:update',
    businessUpdate :'business:update',
    loanUpdate :'loan:update',
    asssetUpdate :'assset:update',
    productsUpdate :'products:update',
    assign_role_productsUpdate :'assign_role_products:update',
    collection_remarkUpdate :'collection_remark:update',
  },
  users: {
    userCreate: 'user:create',
    userEdit: 'user:edit',
    userChange_password: 'user:change_password',
    userStatus: 'user:status',
  }
}