export const URL = {
  base: "http://salesapi.petromoney.in/api/",
  login: "login/user",
  loans: "loans",
  sanction: "loans/sanction",
  dealership: "dealership",
  dealers: "dealers",
  coApplicants: "coapplicants",
  checklist: "checklist",
  applicants: "applicants/dealership",
  salesInfo: "sales/dealership",
  creditInfo: "credit/info",
  creditReport: "credit/report",
  upload: 'upload',
}