export const URL = {
  base: "http://salesapi.petromoney.in/api/",
  login: "login/user",
  loans: "loans",
  sanction: "loans/sanction",
  dealership: "dealership",
  transport: 'transporters',
  dealers: "dealers",
  coApplicants: "coapplicants",
  checklist: "checklist",
  applicants: "applicants/dealership",
  salesInfo: "sales/dealership",
  creditInfo: "credit/info",
  creditReport: "credit/report",
  upload: 'upload',
  ls1_metrices: "business/metrics/ls1",
  ls2_metrices: "business/metrics/ls2",
  loanBook: 'business/loanbook',
}